# Generated by Django 5.1.4 on 2024-12-24 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.CharField(default='No description', max_length=50, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.category', verbose_name='Category'),
        ),
    ]
